"""Scenario configuration dataclasses."""

import re
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ScenarioConfig:
    """
    Single expanded scenario ready for execution.

    Generated by ScenarioGenerator from matrix expansion of scenarios.yaml.
    Contains all configuration needed for a single benchmark run.
    """

    # Identity
    scenario_id: str  # qwen3-0-6b_balanced_direct_tp1
    model_id: str  # Qwen/Qwen3-0.6B
    model_short: str  # qwen3-0-6b

    # Matrix dimensions
    workload: str  # balanced, short, long-context
    routing: str  # direct, prefix-estimation
    tensor_parallel: int  # 1, 2, 4, 8

    # Deployment config
    deployment_name: str  # K8s resource name (sanitized)
    namespace: str = "forge"
    replicas: int = 1

    # vLLM runtime args (merged from common + model + workload)
    runtime_args: dict[str, Any] = field(default_factory=dict)

    # Workload config (from workloads section)
    workload_config: dict[str, Any] = field(default_factory=dict)

    # Routing config (from routing section)
    routing_config: dict[str, Any] = field(default_factory=dict)

    # Model-specific env_vars
    env_vars: dict[str, str] = field(default_factory=dict)

    # Metadata
    description: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "scenario_id": self.scenario_id,
            "model_id": self.model_id,
            "model_short": self.model_short,
            "workload": self.workload,
            "routing": self.routing,
            "tensor_parallel": self.tensor_parallel,
            "deployment_name": self.deployment_name,
            "namespace": self.namespace,
            "replicas": self.replicas,
            "runtime_args": self.runtime_args,
            "config": {
                "workload_config": self.workload_config,
                "routing_config": self.routing_config,
            },
            "env_vars": self.env_vars,
            "description": self.description,
        }

    @staticmethod
    def sanitize_name(name: str, max_len: int = 42) -> str:
        """
        Sanitize name for K8s resource naming.

        Rules:
        - Lowercase
        - Replace / and _ with -
        - Remove dots
        - Truncate to max_len
        """
        return (
            name.lower().replace("/", "-").replace("_", "-").replace(".", "")
        )[:max_len]

    @staticmethod
    def shorten_model_name(model_id: str) -> str:
        """
        Create short model name for scenario_id.

        Examples:
        - Qwen/Qwen3-0.6B -> qwen3-0-6b
        - openai/gpt-oss-120b -> gpt-oss-120b
        - RedHatAI/gpt-oss-120b-FP8-dynamic -> gpt-oss-120b-fp8
        """
        # Take last part after /
        name = model_id.split("/")[-1]

        # Lowercase
        name = name.lower()

        # Remove common suffixes
        for suffix in ["-instruct", "-dynamic", "-chat"]:
            if name.endswith(suffix):
                name = name[: -len(suffix)]

        # Replace dots with dashes
        name = name.replace(".", "-")

        # Truncate version numbers like -2507
        name = re.sub(r"-\d{4}$", "", name)

        return name
