defaults:
  replicas: 1
  tensor_parallelism: 1
  vllm_args:
    - --max-model-len=4096
    - --gpu-memory-utilization=0.92
    - --trust-remote-code
    - --no-enable-log-requests
    - --enable-prefix-caching

approximate-prefix-cache:
  scheduler_manifest: manifests/deployments/approximate-prefix-cache.yaml

precise-prefix-cache:
  scheduler_manifest: manifests/deployments/precise-prefix-cache.yaml

distributed-default:
  scheduler: {}
