# Full pipeline: pre_cleanup -> prepare → test → export-artifacts + post-cleanup.
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: forge-full
  annotations:
    fournos.dev/resolve-image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/forge-core:latest
spec:
  workspaces:
    - name: artifacts
  params:
    - name: fjob-name
      type: string
    - name: fournos-workload-namespace
      type: string
    - name: kubeconfig-secret
      type: string

  tasks:
    - name: 00-pre-cleanup
      taskRef:
        name: forge-step
        kind: Task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-workload-namespace
          value: "$(params.fournos-workload-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: pre-cleanup
        - name: job-step-name
          value: 00__pre-cleanup

    - name: 01-prepare
      runAfter: [00-pre-cleanup]
      taskRef:
        name: forge-step
        kind: Task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-workload-namespace
          value: "$(params.fournos-workload-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: prepare
        - name: job-step-name
          value: 01__prepare

    - name: 02-preflight
      runAfter: [01-prepare]
      taskRef:
        name: forge-step
        kind: Task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-workload-namespace
          value: "$(params.fournos-workload-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: preflight
        - name: job-step-name
          value: 02__preflight

    - name: 03-test
      runAfter: [02-preflight]
      taskRef:
        name: forge-step
        kind: Task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-workload-namespace
          value: "$(params.fournos-workload-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: test
        - name: job-step-name
          value: 03__test

  finally:
    - name: 04-post-cleanup
      taskRef:
        name: forge-step
        kind: Task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-workload-namespace
          value: "$(params.fournos-workload-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: post-cleanup
        - name: job-step-name
          value: 04__post-cleanup

    - name: 05-export-artifacts
      taskRef:
        name: forge-step
        kind: Task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-workload-namespace
          value: "$(params.fournos-workload-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: export-artifacts
        - name: job-step-name
          value: 05__export-artifacts
          # this will instruct FORGET to wait for the post-cleanup to
          # finish before exporting the artifacts
        - name: forge-wait-for-step
          value: 04__post-cleanup
